#####
# Uploads a signed snapshot to sonatype (jar, sources, javadoc)
#####

parameters:
  vmImage: 'ubuntu-20.04'
  jdkVersion: '1.11'
  docker: 'false'

jobs:
- job: UploadSnapshot
  pool:
    vmImage: ${{ parameters.vmImage }}
  dependsOn: Build
  #condition: and(succeeded(), eq(variables['release.version'], ''), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/main')))
  steps:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: secring.gpg
  - task: Gradle@2
    displayName: Upload snapshot
    inputs: 
      gradleWrapperFile: 'gradlew'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: ${{ parameters.jdkVersion }}
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      tasks: 'publishToNexus -x test'
      options: '--info --stacktrace'
    env:
      SIGNING_SECRET_KEY_RING_FILE: $(Agent.TempDirectory)/secring.gpg 
      SIGNING_PASSWORD: $(signing.password)
      SIGNING_KEY_ID: $(signing.keyId)
      OSSRH_USERNAME: $(ossrh.username)
      OSSRH_PASSWORD: $(ossrh.password)
      CI: true
  - ${{ if eq(parameters.docker, 'true') }}:
    - download: current
      artifact: tarImage
      displayName: Download jib image
    - script: docker load --input $(Pipeline.Workspace)/tarImage/jib-image.tar
      displayName: Load image to docker

    - task: Docker@2
      displayName: Publish docker
      inputs:
        command: push
        repository: $(Build.Repository.Name)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: $(Build.BuildNumber)
