stages:
- stage: Testing
  jobs:
  - job: 'Test'
    pool:
      vmImage: 'ubuntu-18.04'
    strategy:
      matrix:
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
        Python38:
          python.version: '3.8'

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'

    - script: pip install flit
      displayName: 'Install flit build tool'

    - script: flit install
      displayName: 'Install library and its dependencies'

    - script: pytest
      displayName: 'Run tests'

- stage: "Publish"
  condition: and(succeeded(),  ne(variables['release.version'], ''), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  pool:
    vmImage: 'ubuntu-18.04'
  jobs:
    - job: "PublishPyPi"
      steps:

        - checkout: self
          persistCredentials: true

        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.7'

        - script: pip install pip --upgrade
          displayName: "Upgrade pip"

        - script: pip install flit
          displayName: 'Install flit'

        - script: flit install
          displayName: 'Install library'

        - script: |
            git config user.email "31185348+bakdata-bot@users.noreply.github.com"
            git config user.name "bakdata-bot"
            git fetch
            git checkout master
          displayName: "Setting GitHub author"

        - script: bump2version $(release.version)
          displayName: "Bump version"

        - script: flit build
          displayName: "Build library"

        - script: git push --follow-tags origin master
          displayName: "Pushing tag to github"

        - script: flit publish 
          displayName: "Publish to PyPi"
          env:
            FLIT_INDEX_URL: $(pypi.url)
            FLIT_USERNAME: $(pypi.username)
            FLIT_PASSWORD: $(pypi.password)
            FLIT_ROOT_INSTALL: 1
